version: '3'

services:
  drone-server:
    image: drone/drone:2
    container_name: drone-server
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - drone-data:/data
    environment:
      - DRONE_SERVER_HOST=localhost:8080
      - DRONE_SERVER_PROTO=http
      - DRONE_DEBUG=true
      - DRONE_GITHUB_CLIENT_ID=Ov23lijNp3rS7wK8IN8o
      - DRONE_GITHUB_CLIENT_SECRET=ccf501ee775bc97bf82772179fc835b1a179609d
      - DRONE_RPC_SECRET=a4d8d7be647d581a548af4aa99554bab
      - DRONE_USER_CREATE=username:boloftech,admin:true
    restart: always

  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: drone-runner
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_SECRET=9f9d51bc70ef21ca5c14f307980a29d8
      - DRONE_RUNNER_CAPACITY=2
    restart: always

volumes:
  drone-data:
